out:
  [[1, 1],
  [2.5, 1],
  [2.5, 2.5],
  [1, 2.5]]

home:
  [[3.0, 9],
  [4.5, 9],
  [6.0, 9],
  [7.5, 9]]

shared:
  [[1.5, 7.5],
  [3.0, 7.5],
  [4.5, 7.5],
  [6.0, 7.5],
  [7.5, 7.5],
  [7.5, 6.0],
  [7.5, 4.5],
  [7.5, 3.0],
  [7.5, 1.5],
  [9.0, 1.5]]